# Generated by Django 3.2.8 on 2022-03-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('PlayerImg', models.ImageField(upload_to='media/')),
                ('From', models.CharField(max_length=120, verbose_name='From Where')),
                ('PlayerName', models.CharField(max_length=120, verbose_name='Player Name')),
                ('MsgBody', models.CharField(max_length=550, verbose_name='Mensagem')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('username', models.CharField(max_length=120, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.CharField(max_length=120, verbose_name='password')),
                ('password2', models.CharField(max_length=120, verbose_name='Confirm password')),
            ],
            bases=('app.base',),
        ),
    ]
