# Generated by Django 3.2.8 on 2022-03-24 04:53

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('MsgBody', models.TextField(max_length=550, verbose_name='Msg')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('PlayerImg', stdimage.models.StdImageField(upload_to='Profile', verbose_name='Imagem')),
                ('From', models.CharField(max_length=120, verbose_name='From Where')),
                ('PlayerName', models.CharField(max_length=120, verbose_name='Player Name')),
                ('MsgBody', models.TextField(max_length=550, verbose_name='Mensagem')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('username', models.CharField(max_length=120, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.CharField(max_length=120, verbose_name='password')),
                ('password2', models.CharField(max_length=120, verbose_name='Confirm password')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('username', models.CharField(max_length=120, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.CharField(max_length=120, verbose_name='password')),
                ('password2', models.CharField(max_length=120, verbose_name='Confirm password')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='MegaProfile',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
                ('UserImg', stdimage.models.StdImageField(upload_to='Profile', verbose_name='Imagem')),
                ('UserFrom', models.CharField(max_length=120, verbose_name='From Where')),
                ('UserPlayerName', models.CharField(max_length=120, verbose_name='Player Name')),
                ('UserMsgBody', models.TextField(max_length=550, verbose_name='Mensagem')),
            ],
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Like', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feedpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='feedpost',
            name='Likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='FeedPost', to='app.User'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.user'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('Msg', models.CharField(max_length=120, verbose_name='comment')),
                ('LikesComm', models.ManyToManyField(blank=True, default=None, related_name='Comments', to='app.User')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
