# Generated by Django 3.2.8 on 2022-03-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='MsgBody',
            field=models.TextField(max_length=550, verbose_name='Mensagem'),
        ),
    ]
