# Generated by Django 3.2.8 on 2022-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaprofile',
            name='UserProfessionAt',
            field=models.CharField(blank=True, max_length=120, verbose_name='Profession at'),
        ),
    ]
