# Generated by Django 3.2.8 on 2022-03-23 01:00

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_playerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PlayerImg',
            field=stdimage.models.StdImageField(upload_to='Profile', verbose_name='Imagem'),
        ),
    ]
