# Generated by Django 3.2.8 on 2022-03-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_playerimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('username', models.CharField(max_length=120, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.CharField(max_length=120, verbose_name='password')),
                ('password2', models.CharField(max_length=120, verbose_name='Confirm password')),
            ],
            bases=('app.base',),
        ),
    ]
