# Generated by Django 3.2.8 on 2022-03-23 06:17

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaProfile',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
                ('UserImg', stdimage.models.StdImageField(upload_to='Profile', verbose_name='Imagem')),
                ('UserFrom', models.CharField(max_length=120, verbose_name='From Where')),
                ('UserPlayerName', models.CharField(max_length=120, verbose_name='Player Name')),
                ('UserMsgBody', models.TextField(max_length=550, verbose_name='Mensagem')),
            ],
            bases=('app.usuario',),
        ),
    ]
