# Generated by Django 3.2.8 on 2022-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comments_feedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='LikesComm',
            field=models.ManyToManyField(related_name='Comments', to='app.User'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='Likes',
            field=models.ManyToManyField(related_name='FeedPost', to='app.User'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
