# Generated by Django 3.2.8 on 2022-03-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220323_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='LikesComm',
            field=models.ManyToManyField(blank=True, default=None, related_name='Comments', to='app.User'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='Likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='FeedPost', to='app.User'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Like', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feedpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
