# Generated by Django 3.2.8 on 2022-03-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220323_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='LikesComm',
            field=models.ManyToManyField(blank=True, default=None, related_name='Comments', to='app.User'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
